// Code generated by scripts/build_ortools.sh; DO NOT EDIT.
// Содержимое bind.o меняется — файл форсирует перекомпиляцию пакета
// solver (кэш cgo не видит изменений внешнего bind.o из LDFLAGS).
package solver

// bindObjectHash — контрольная сумма bind.o, вшитая при сборке биндинга.
const bindObjectHash = "227664369438a44988d75158cff005f1"
