// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {io} from '../models';
import {solver} from '../models';

export function CreateClass(arg1:domain.SchoolClass):Promise<domain.SchoolClass>;

export function CreateConstraint(arg1:domain.Constraint):Promise<domain.Constraint>;

export function CreateLesson(arg1:domain.Lesson):Promise<domain.Lesson>;

export function CreateRoom(arg1:domain.Room):Promise<domain.Room>;

export function CreateSchool(arg1:string):Promise<domain.School>;

export function DeleteSchool(arg1:number):Promise<void>;

export function SchoolHasLessons(arg1:number):Promise<boolean>;

export function SchoolHasSchedule(arg1:number):Promise<boolean>;

export function CreateSubject(arg1:domain.Subject):Promise<domain.Subject>;

export function CreateTeacher(arg1:domain.Teacher):Promise<domain.Teacher>;

export function DeleteClass(arg1:number):Promise<void>;

export function DeleteConstraint(arg1:number):Promise<void>;

export function DeleteLesson(arg1:number):Promise<void>;

export function DeleteRoom(arg1:number):Promise<void>;

export function DeleteScheduleEntry(arg1:number):Promise<void>;

export function DeleteSubject(arg1:number):Promise<void>;

export function DeleteTeacher(arg1:number):Promise<void>;

export function ExportAll(arg1:number):Promise<io.Snapshot>;

export function ExportRefsCSV(arg1:number,arg2:string):Promise<string>;

export function Generate(arg1:number,arg2:number,arg3:number):Promise<solver.Result>;

export function GeneratePrecise(arg1:number,arg2:number,arg3:number):Promise<solver.Result>;

export function GetSchoolSettings(arg1:number):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportAll(arg1:string):Promise<void>;

export function ImportRefsCSV(arg1:number,arg2:string,arg3:string):Promise<number>;

export function ListClasses(arg1:number):Promise<Array<domain.SchoolClass>>;

export function ListConstraints(arg1:number):Promise<Array<domain.Constraint>>;

export function ListLessons(arg1:number):Promise<Array<domain.Lesson>>;

export function ListRooms(arg1:number):Promise<Array<domain.Room>>;

export function ListSchedule(arg1:number):Promise<Array<domain.ScheduleEntry>>;

export function ListSchools():Promise<Array<domain.School>>;

export function ListSubjects(arg1:number):Promise<Array<domain.Subject>>;

export function ListTeachers(arg1:number):Promise<Array<domain.Teacher>>;

export function MoveEntry(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SwapEntries(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number):Promise<void>;

export function ReplaceSchedule(arg1:number,arg2:Array<domain.ScheduleEntry>):Promise<void>;

export function SaveExport(arg1:string,arg2:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileWithDialog(arg1:string):Promise<string>;

export function ScheduleCSV(arg1:number,arg2:number,arg3:number):Promise<string>;

export function UpdateLesson(arg1:domain.Lesson):Promise<domain.Lesson>;

export function UpdateSchoolSettings(arg1:number,arg2:string):Promise<void>;
