// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateClass(arg1) {
  return window['go']['main']['App']['CreateClass'](arg1);
}

export function CreateConstraint(arg1) {
  return window['go']['main']['App']['CreateConstraint'](arg1);
}

export function CreateLesson(arg1) {
  return window['go']['main']['App']['CreateLesson'](arg1);
}

export function CreateRoom(arg1) {
  return window['go']['main']['App']['CreateRoom'](arg1);
}

export function CreateSchool(arg1) {
  return window['go']['main']['App']['CreateSchool'](arg1);
}

export function CreateSubject(arg1) {
  return window['go']['main']['App']['CreateSubject'](arg1);
}

export function CreateTeacher(arg1) {
  return window['go']['main']['App']['CreateTeacher'](arg1);
}

export function DeleteClass(arg1) {
  return window['go']['main']['App']['DeleteClass'](arg1);
}

export function DeleteConstraint(arg1) {
  return window['go']['main']['App']['DeleteConstraint'](arg1);
}

export function DeleteLesson(arg1) {
  return window['go']['main']['App']['DeleteLesson'](arg1);
}

export function DeleteRoom(arg1) {
  return window['go']['main']['App']['DeleteRoom'](arg1);
}

export function DeleteScheduleEntry(arg1) {
  return window['go']['main']['App']['DeleteScheduleEntry'](arg1);
}

export function DeleteSchool(arg1) {
  return window['go']['main']['App']['DeleteSchool'](arg1);
}

export function DeleteSubject(arg1) {
  return window['go']['main']['App']['DeleteSubject'](arg1);
}

export function DeleteTeacher(arg1) {
  return window['go']['main']['App']['DeleteTeacher'](arg1);
}

export function ExportAll(arg1) {
  return window['go']['main']['App']['ExportAll'](arg1);
}

export function ExportPDF(arg1, arg2) {
  return window['go']['main']['App']['ExportPDF'](arg1, arg2);
}

export function ExportRefsCSV(arg1, arg2) {
  return window['go']['main']['App']['ExportRefsCSV'](arg1, arg2);
}

export function Generate(arg1, arg2, arg3) {
  return window['go']['main']['App']['Generate'](arg1, arg2, arg3);
}

export function GeneratePrecise(arg1, arg2, arg3) {
  return window['go']['main']['App']['GeneratePrecise'](arg1, arg2, arg3);
}

export function GetSchoolSettings(arg1) {
  return window['go']['main']['App']['GetSchoolSettings'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HasPreciseSolver() {
  return window['go']['main']['App']['HasPreciseSolver']();
}

export function ImportAll(arg1) {
  return window['go']['main']['App']['ImportAll'](arg1);
}

export function ImportRefsCSV(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportRefsCSV'](arg1, arg2, arg3);
}

export function ListClasses(arg1) {
  return window['go']['main']['App']['ListClasses'](arg1);
}

export function ListConstraints(arg1) {
  return window['go']['main']['App']['ListConstraints'](arg1);
}

export function ListLessons(arg1) {
  return window['go']['main']['App']['ListLessons'](arg1);
}

export function ListRooms(arg1) {
  return window['go']['main']['App']['ListRooms'](arg1);
}

export function ListSchedule(arg1) {
  return window['go']['main']['App']['ListSchedule'](arg1);
}

export function ListSchools() {
  return window['go']['main']['App']['ListSchools']();
}

export function ListSubjects(arg1) {
  return window['go']['main']['App']['ListSubjects'](arg1);
}

export function ListTeachers(arg1) {
  return window['go']['main']['App']['ListTeachers'](arg1);
}

export function MoveEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveEntry'](arg1, arg2, arg3);
}

export function ReplaceSchedule(arg1, arg2) {
  return window['go']['main']['App']['ReplaceSchedule'](arg1, arg2);
}

export function SaveExport(arg1, arg2) {
  return window['go']['main']['App']['SaveExport'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileWithDialog(arg1) {
  return window['go']['main']['App']['SaveFileWithDialog'](arg1);
}

export function ScheduleCSV(arg1, arg2, arg3) {
  return window['go']['main']['App']['ScheduleCSV'](arg1, arg2, arg3);
}

export function SchoolHasLessons(arg1) {
  return window['go']['main']['App']['SchoolHasLessons'](arg1);
}

export function SchoolHasSchedule(arg1) {
  return window['go']['main']['App']['SchoolHasSchedule'](arg1);
}

export function SwapEntries(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SwapEntries'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateLesson(arg1) {
  return window['go']['main']['App']['UpdateLesson'](arg1);
}

export function UpdateSchoolSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateSchoolSettings'](arg1, arg2);
}
